site_name: SSO API Documentation
site_description: Comprehensive documentation for the Single Sign-On API
site_author: Integrichain Development Team
site_url: https://andresdigi25.github.io/single-sign-on

# Repository
repo_name: andresdigi25/single-sign-on
repo_url: https://github.com/andresdigi25/single-sign-on
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  language: en
  
  # Color scheme
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  # Features
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - content.action.view
  
  # Icons and logos
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  
  # Font
  font:
    text: Roboto
    code: Roboto Mono

# Navigation
nav:
  - Home: index.md
  - User Guide: user-guide.md
  - Tutorials: tutorials.md
  - Architecture: architecture.md
  - FAQ: faq.md

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: integrichain
      repo: single-sign-on
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - mermaid2:
      arguments:
        theme: base
        themeVariables:
          primaryColor: '#1976d2'
          primaryTextColor: '#ffffff'

# Extra
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.integrichain.net/ProductEngineering/integrichain-admin
    - icon: fontawesome/solid/globe
      link: https://integrichain.net
  
  # Analytics (if needed)
  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Copyright
copyright: Copyright &copy; 2024 Integrichain - All rights reserved